services:
  backend:
    build: ./backend
    restart: unless-stopped
    container_name: ld-portal-backend-1
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
      - JWT_SECRET=${JWT_SECRET:-bitte-aendern-openssl-rand-hex-32}
    volumes:
      - app-data:/data
    networks:
      - app-network

  caddy:
    build: ./caddy
    restart: unless-stopped
    container_name: ld-portal-caddy-1
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - app-data:/app-data
      - app-data:/data
      - caddy-config:/config
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: ld-portal-frontend-1
    ports:
      - "8081:81"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
